In [1]:

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import datasets


In [32]:
#load the iris dataset
iris = datasets.load_iris()
X = iris.data[:, :]  
y = (iris.target != 0) * 1 

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [33]:
#model formulation and training
model = LogisticRegression()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

accuracy = np.mean(predictions == y_test)
print(f"Accuracy: {accuracy}")


Accuracy: 1.0


In [34]:
coefficients = model.coef_
intercept = model.intercept_

**Weights of the first model are given as:**

In [35]:
coefficients

array([[ 0.42775966, -0.88797565,  2.2135352 ,  0.91847975]])

In [36]:
intercept

array([-6.24278552])

**Duplicating the nth feature**

In [37]:
X_ = np.concatenate((X, iris.data[:,-1].reshape(-1,1)), axis = 1)

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X_, y, test_size=0.2, random_state=42)

model = LogisticRegression()

# Training the model on the training data
model.fit(X_train, y_train)

# Making predictions on the test set
predictions = model.predict(X_test)

# Evaluating the model
accuracy = np.mean(predictions == y_test)
print(f"Accuracy: {accuracy}")


Accuracy: 1.0


In [39]:
coefficients2 = model.coef_
intercept2 = model.intercept_

**New model weights**

In [40]:
coefficients2

array([[ 0.38859867, -0.83459664,  2.02838282,  0.82272319,  0.82272319]])

In [41]:
intercept2 

array([-6.23141507])

In [49]:
np.mean(coefficients2) + intercept2

array([-5.58584882])

In [50]:
np.mean(coefficients) + intercept

array([-5.57483578])

Since the newly added feature is corelated with the last feature, the model distributes the weights between different features so that the last two have similar weights (which is how it should be since they're the same values). Also, other weights get affected because of which. I find that the mean of all weights remains same before and after adding of this corelated feature.